### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by jensadev** [Aragorn173/jsquiz#1]
Fundera ut hur datan du ska skicka till din backend ska se ut.
Vad är det du vill spara och hur ska det sparas?
Är det all data eller inte?

När du väl kan skapa ett JSON object med detta i frontend, då kan vi redigera glitch projectet att acceptera datan.

Siffror i js parseInt()

**Comment by Aragorn173** [comment]
Nu är detta fixat 😃😃😃
